### ISSUE TITLE
docs: use `eslint-doc-generator`

### ISSUE THREAD

**Issue by MichaelDeBoey** [ota-meshi/eslint-plugin-regexp#476]
@bmish created this awesome library that brings a unified way of rule docs
https://github.com/bmish/eslint-doc-generator

**Comment by ota-meshi** [comment]
I think that library is worth a try.
However, we configure the script to automatically mark the release version of the rules, so it may be difficult to use that library.

e.g. https://github.com/ota-meshi/eslint-plugin-regexp/commit/8cffcede4f95075af6fc0226cef6cfbc5964fa89#diff-a94087d993ec67e6fceedea0f6b9469c1cef47877617a79bd80c3f1d21a12094R6

**Comment by bmish** [comment]
> However, we configure the script to automatically mark the release version of the rules, so it may be difficult to use that library.

eslint-doc-generator doesn't manage the entire rule doc so I think that's fine and not an issue.

However, I looked into adding eslint-doc-generator to this plugin and found several blockers due to the use of the static site generator:

* https://github.com/bmish/eslint-doc-generator/issues/252
* https://github.com/bmish/eslint-doc-generator/issues/253
* https://github.com/bmish/eslint-doc-generator/issues/254

**Comment by bmish** [comment]
I've addressed all those blockers and opened #493.
