### ISSUE TITLE
provide some fix example on bad practices?

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin-regexp#531]
For example, [no-potentially-useless-backreference](https://ota-meshi.github.io/eslint-plugin-regexp/rules/no-potentially-useless-backreference.html) reports `/(a)?b\1/` as issue, but I'm not for sure how to fix it which is preferred by this rule?

**Comment by ota-meshi** [comment]
I think we can fix it like `/(a?)b\1/`.

**Comment by JounQin** [comment]
😅 What about `/(axyz)?b\1/`?

**Comment by RunDevelopment** [comment]
> 😅 What about `/(axyz)?b\1/`?

One solution would be `/((?:axyz)?)b\1/`, but it's not very nice. 

I personally prefer ``/(axyz)b\1|b/`` since it makes the 2 distinct cases (and the order in which they are tested) very visible, but it comes with a bit of code duplication. This might not be bad though. From my experience, this type of pattern (`/(a)?b\1/`) typically happens with optionally quoted text. Since the cases `(a)b\1` and just `b` typically require slightly different patterns for `b`, this code duplication will likely nudge devs towards making a more correct (if longer) regex.

I'll add a bit of text to the docs.
