### ISSUE TITLE
`regexp/prefer-range` and not obvious cases

### ISSUE THREAD

**Issue by zloirock** [ota-meshi/eslint-plugin-regexp#55]
Could you add an option to make this rule work only with obvious cases, but not with cases like those?

`/[!'()~]|%20/g`
> Unexpected multiple adjacent characters. Use "'-)" instead

`/^[\u0000-\u001F ]+|[\u0000-\u001F ]+$/g`
> Unexpected multiple adjacent characters. Use "\u0000- " instead

**Comment by ota-meshi** [comment]
Thank you for the request!

What do you think about adding the following options?

**Proposal 1**: Add the `ignoreSymbols: true` option.
Enabling this option excludes U+0020(space) - U+002F(/), U+003A(:) - U+0040(@), U+005B([) - U+0060(`), U+007B({) - U+007E(~), and characters containing them will not try to combine using a range.
Symbolic letters are not as easy to order as alphabets and numbers. By not using ranges in these, you prevent readability degradation.

**Proposal 2**: Add the `ignoreCharacters: [...]` option.
If the user specifies a character in the option, that character is excluded and characters containing them will not try to combine using a range.
Perhaps most users can specify their preferences, but it can be difficult to set up.

Also, let me know if you have any option ideas.

**Comment by zloirock** [comment]
They both look like valid options. I think that something like `alphanumeric: true` could be a simpler alternative option.

**Comment by ota-meshi** [comment]
Thank you for your comment!
I would like to add the following option inspired by your idea.

`{ "target": "..."}` Option.

- `{ "target": "alphanumeric" }` ... Check your use of alphabets and numbers, and report if they can be replaced with a range. (Change it rule so that this is the default.)
- `{ "target": "all" }` ... Check your use of all characters, and report if they can be replaced with a range.
- `{ "target": [ "alphanumeric", "①-⑳", "⑴-⒇", ... ] }` ... Check your use of alphanumeric characters and your specified character range, such as from ①(U+2460) to ⑳(U+2473) characters, and report if they can be replaced with a range.

This option can almost prevent the readability from being reduced by replacing the user's unfamiliar character code with a range. If you want to focus on regular expression optimization, you can also use `"all"` to check all characters.
