### ISSUE TITLE
Support flat config (eslint.config.js)

### ISSUE THREAD

**Issue by fisker** [ota-meshi/eslint-plugin-regexp#695]
See https://eslint.org/docs/latest/use/configure/configuration-files-new

**Comment by ota-meshi** [comment]
I'm still wondering how best practice is to export a new shareable configuration 🤔 
I would like to export using the same method as the popular eslint-plugin, but I don't know what it is yet.

Otherwise, I can think of the following method:

- Use `configs.recommended` namespace.
  `plugin.configs.recommended` is reserved for legacy configurations.
  I don't want to change it for backwards compatibility.
- Use a new namespace.
  I don't want to use names like `plugin.flatConfigs.recommended`, and `plugin.configs.flatRecommended`. "Flat" quickly becomes meaningless.
  Also, I think it is difficult to understand the difference between `config` and `configs`.
  I'm not sure what namespace to use instead that would be easier for people to use.
- Use new `*.js` file. 
   e.g. `import { recommended } from 'eslint-plugin-regexp/configs'`.
- Make `plugin.configs` an object-like function with properties.
   e.g. `plugin.configs('recommended')`.

**Comment by ota-meshi** [comment]
Thank you for sharing the discussion! I will check it.

**Comment by bradzacher** [comment]
Note: @typescript-eslint is using a new package because we have both the plugin and the parser.

The advice from upstream is the breaking change approach - though I don't like it, personally as it's making second class citizens of users not on flat configs.

There's no specific reason that you need to make it available on the `.config` export of your package. You could also do it as a different exported name, or a separate path (`eslint-plugin-regexp/config`).

**Comment by fisker** [comment]
Unicorn didn't use `/config` because this requires `exports` to be added in package.json, since it should support both import and require.
